#!/usr/bin/env python

import argparse
#import os

from proxy_negotiate import NegotiateProxy

parser = argparse.ArgumentParser(description='A proxy server for applications '
                                 'that do not natively support Negotiate '
                                 'authentication for proxies.')
parser.add_argument('proxy_host', help='Hostname of the proxy server.')
parser.add_argument('proxy_port', help='Port of the proxy server.', type=int)
parser.add_argument('--host', help='Hostname or IP to listen for connections on.',
                    default='127.0.0.1')
parser.add_argument('--port', help='Port to listen for connections on.',
                    type=int, default=8080)
args = parser.parse_args()

print(f"Initiating proxy")
print(f"Listening on: {args.host}:{args.port}\n",
      f"Forwarding to: {args.proxy_host}:{args.proxy_port}")
proxy = NegotiateProxy((args.host, args.port), (args.proxy_host, args.proxy_port))
proxy.serve_forever()
